name: Build and Deploy
run-name: Build and Upload Image
on: [push]
jobs:
  container-build:
    runs-on: anki-sync-server-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix Deps
        run: sudo apt update && sudo apt install xz-utils
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build container
        run: nix build .#docker
      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: container.tar
          path: ./result
      - name: Upload flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: flake.lock
          path: flake.lock
  container-push:
    runs-on: anki-sync-server-runners
    needs: container-build
    steps:
      - name: Download container tar
        uses: actions/download-artifact@v4
        with:
          name: container.tar
      - name: Download flake lock
        uses: actions/download-artifact@v4
        with:
          name: flake.lock
      - name: Load container image
        run: docker load < result
      - name: Tag image
        run: |
          REV=$(jq -r .nodes.nixpkgs.locked.rev flake.lock)
          echo "REV=$REV" >> "$GITHUB_ENV"
          docker tag cbingman/anki-sync-server:latest cbingman/anki-sync-server:$GITHUB_SHA-$REV
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            docker tag cbingman/anki-sync-server:latest cbingman/anki-sync-server:$GITHUB_REF_NAME-$REV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push latest to repo
        run: "docker push cbingman/anki-sync-server:latest"
      - name: Push image to repo
        run: "docker push cbingman/anki-sync-server:$GITHUB_SHA-$REV"
      - name: Push production image
        if: github.ref_type == 'tag'
        run: "docker push cbingman/anki-sync-server:$GITHUB_REF_NAME-$REV"
  update-chart:
    runs-on: anki-sync-server-runners
    needs: container-build
    if: github.ref_type == 'tag'
    steps:
      - name: Download flake lock
        uses: actions/download-artifact@v4
        with:
          name: flake.lock
      - name: Checkout helm repo
        uses: actions/checkout@v4
        with:
          repository: ChristianBingman/anki-sync-server-chart
          token: ${{ secrets.HELM_PAT }}
          ref: main
          path: chart
      - name: Setup env
        run: |
          REV=$(jq -r .nodes.nixpkgs.locked.rev flake.lock)
          echo "COMMIT_TAG=$GITHUB_REF_NAME-$REV" >> "$GITHUB_ENV"
      - name: Update int environment
        run: |
          cd chart
          sed -i -e "s/appVersion: .*$/appVersion: \"$COMMIT_TAG\"/g" Chart.yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
          git add Chart.yaml
          git commit -m "Deploy [prod]"
          git push
