name: Build and Deploy
run-name: Build and Upload Image
on: [push]
jobs:
  container-build:
    runs-on: anki-sync-server-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix Deps
        run: sudo apt update && sudo apt install xz-utils
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build container
        run: nix build .#docker
      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: container.tar
          path: ./result
      - name: Upload flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: flake.lock
          path: flake.lock
  container-push:
    runs-on: anki-sync-server-runners
    needs: container-build
    steps:
      - name: Download container tar
        uses: actions/download-artifact@v4
        with:
          name: container.tar
      - name: Download flake lock
        uses: actions/download-artifact@v4
        with:
          name: flake.lock
      - name: Load container image
        run: docker load < result
      - name: Tag image
        run: |
          REV=$(jq -r .nodes.nixpkgs.locked.rev flake.lock)
          echo "REV=$REV" >> "$GITHUB_ENV"
          docker tag cbingman/anki-sync-server:latest cbingman/anki-sync-server:$GITHUB_SHA-$REV
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            docker tag cbingman/anki-sync-server:latest cbingman/anki-sync-server:$GITHUB_REF_NAME-$REV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push latest to repo
        run: "docker push cbingman/anki-sync-server:latest"
      - name: Push image to repo
        run: "docker push cbingman/anki-sync-server:$GITHUB_SHA-$REV"
      - name: Push production image
        if: github.ref_type == 'tag'
        run: "docker push cbingman/anki-sync-server:$GITHUB_REF_NAME-$REV"
